### PR TITLE
Add today&yesterday options when listing records

### PR DESCRIPTION
**Pull request by rocar**
This PR added today and yesterday options to the list command for issue https://github.com/dominikbraun/timetrace/issues/30

### CODE REVIEW

**Review by dominikbraun — CHANGES_REQUESTED** [review]
Looks perfect, thanks 👍 Could you maybe update the new argument syntax (`records {<YYYY-MM-DD>|today|yesterday}`) in README.md as well?

**Comment by rocar** [comment]
Thanks for reminding. Updated the argument syntax

**Review by dominikbraun — APPROVED** [review]
Thanks! I really need this feature 😅 

LGTM

**Comment by dominikbraun** [comment]
This PR is included in [release v0.3.1](https://github.com/dominikbraun/timetrace/releases/tag/v0.3.1).

**Pull request merged**
