### PR TITLE
#139 Added a separate method for duration calculation

### PR DESCRIPTION
**Pull request by alksmt**
PR for #139 

Moving duration calculation to a separate Duration method, including cases when a record is still being tracked.

### CODE REVIEW

**Review by dominikbraun — APPROVED** [review]
LGTM, thanks! 👍

**Comment by dominikbraun** [comment]
@alksmt A PR has been merged that still contained two `record.End.Sub(record.Start)` calls. Would you like to replace them as well before this PR gets merged or should I do this myself? 😄

**Comment by alksmt** [comment]
@dominikbraun replaced this entries and found another one for status command, PR is up to date with `main` branch

**Comment by dominikbraun** [comment]
@alksmt Thanks!

**Pull request merged**
