### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by jwnpoh**
Addresses #148.

### CODE REVIEW

**Comment by jwnpoh** [comment]
Sorry, it seems I have also included my commit for another issue into this PR. This is the first project that I'm submitting PRs for so apologies for the repeat commit. I'm not sure how to undo/rectify this repetition; would appreciate it greatly if someone could kindly provide some guidance on this!

**Comment by aligator** [comment]
Hi, thanks for your PRs,

That's no problem, we will handle this :-)

**Comment by jwnpoh** [comment]
That's good to know, thanks!

**Comment by dominikbraun** [comment]
@jwnpoh: #147 is now merged. This means that you can [update your timetrace fork](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) and then merge `main` into your `readme` branch. Since the confirmation-related changes are already included in your branch after merging `main`, they won't appear in this PR anymore.

**Comment by jwnpoh** [comment]
I see. Thanks for the pointers! I'll do that once I get home to my machine.

**Comment by jwnpoh** [comment]
Thanks for the pointers! I'll give it a try even if only just to get a better grasp of how branching and merging works.

**Review by aligator — APPROVED** [review]
LGTM

**Comment by dominikbraun** [comment]
Nice, as you can see your merge created a merge commit and the confirmation-related changes don't appear as difference anymore, because they're now included in the target branch.

**Review by dominikbraun — APPROVED** [review]
LGTM

**Comment by dominikbraun** [comment]
This PR is included in [timetrace v0.11.1](https://github.com/dominikbraun/timetrace/releases/tag/v0.11.1).

**Pull request merged**
